server:
    port: 8181
spring:
    datasource:
      username: root
      password: lhb980601
      url: jdbc:mysql://localhost:3306/fixersystem?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true